# Generated by Django 5.1.15 on 2026-06-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_label_bridge', '0001_initial'),
        ('organizations', '0006_alter_organizationmember_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeOrganizationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opentrain_organization_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_label_bridge_link', to='organizations.organization')),
            ],
            options={
                'db_table': 'open_label_bridge_organization_link',
            },
        ),
    ]
